### ISSUE TITLE
Cannot download speedtest.net configuration

### ISSUE THREAD

**Issue by doragasu** [mobrembski/SpeedTestC#5]
Although this worked in the past, currently the client fails to download speedtest.net configuration and exits:

```
$ ./SpeedTestC
Http error while creating GET request socket: 301
Cannot download speedtest.net configuration. Something is wrong...
```
It seems the client fails to do a server redirect.

**Comment by mobrembski** [comment]
Indeed, but it looks like it is a more serious problem.
It looks like now all communication is sent by HTTPS, and dealing with SSL on very low level is quite complicated.
I will think how to solve it.

**Comment by doragasu** [comment]
I see. Thanks for checking it!

**Comment by nzamps** [comment]
Maybe time to use libcurl  ?

**Comment by mobrembski** [comment]
Or just openssl. not sure which library footprint is lower, but i believe openssl libraries are more common on embedded systems than libcurl (remember origin of this project was to bring Speedtest client to embedded platforms).

**Comment by nzamps** [comment]
Openssl is relatively huge - more likely to use an alternative on embedded like polarssl, GnuTLS or Wolfssl (cyassl) - libcurl supports these and others...and works well on almost anything. We use Wolfssl on our embedded systems which are MIPS and ARM and its tiny compared with openssl!

**Comment by Monter** [comment]
Any solution...?

**Comment by mobrembski** [comment]
Not for now, sorry, i havent got time

śr., 27.03.2019, 13:55 użytkownik Mark eM <notifications@github.com>
napisał:

**Comment by mobrembski** [comment]
Done by @philbudne :)

**Comment by feishengfei** [comment]
zhouX@XA005S:~/SpeedTestC_new$ ./SpeedTestC 
Http error while creating GET request socket: 429
Cannot download speedtest.net configuration. Something is wrong...

**Comment by philbudne** [comment]
I had noticed some time ago that SpeedTestC was being blocked based on the User-Agent string, but  figured it might be transient.  I've opened a PR with a fix: https://github.com/mobrembski/SpeedTestC/pull/8

NOTE!!! While the error message might be the same, this is not the same underlying cause (SSL vs User-Agent string)


Might be wise/useful to find out WHY the old UA was being blocked (perhaps because it wasn't very descriptive)?
